/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.andrake_testing.helloandroid;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int blue=0x7f030003;
        public static final int green=0x7f030002;
        public static final int red=0x7f030001;
        public static final int white=0x7f030000;
        public static final int yellow=0x7f030004;
    }
    public static final class layout {
        public static final int main=0x7f020000;
    }
    public static final class string {
        public static final int app_name=0x7f040002;
        public static final int externalized_string=0x7f040000;
        public static final int hello=0x7f040001;
    }
}
